#!/bin/bash

GARUPA=(kasumi tae rimi arisa saya \
        ran mocha himari tsugumi tomoe \
        aya hina chisato eve maya \
        yukina sayo risa rinko ako \
        kokoro kaoru hagumi michelle kanon \
        reiya lock masking pareo chuchu \
        marina misaki)
alias garupa='echo ${GARUPA[$((RANDOM % 32))]}'

alias le='less -RCS'
alias lx='less -RCSX'
alias nginx='/etc/init.d/nginx'
alias shutdown='sudo /sbin/shutdown -h now'
alias reboot='sudo /sbin/shutdown -r now'
alias vimt='vim -c NERDTree'
alias blue='echo -e "\e[44m"; echo -e "\e[40m"'
alias setclock='ntpdate -v ntp.nict.jp' # Set a clock by JMT.
alias yaml="ruby -r yaml -r pp -e 'pp YAML.load(ARGF.read())'" # Load yaml.

alias remove='rm -i'
alias copy='cp -i'
alias move='mv -i'

alias ..='cd ../; echo "---------------";'
alias ...='.. ..'
alias ....='.. .. ..'

blackout()
{
  tput -S << EOF
clear
cup `tput cols` 0
EOF
}

hs()
{
  expr "$2" + 1 > /dev/null 2>&1
  if [ $? -lt 2 ]; then
    history | grep -E "$1" | tail -$2
  else
    history | grep -E "$1" | tail
  fi
}

hv()
{
  expr "$2" + 1 > /dev/null 2>&1
  if [ $? -lt 2 ]; then
    history | grep -E "$1" | tail -$2 | cut -c 8- | view -
  else
    history | grep -E "$1" | tail | cut -c 8- | view -
  fi
}

lf()
{
  while [ $1 ]
  do
    if [ "${1:0:1}" = "-" ]; then
      local OPT="$OPT $1"
    else
      local ARGS="$ARGS $1"
    fi
    shift
  done

  find $ARGS -maxdepth 1 -print0 | xargs -0 ls -d | ~/.shells/print0 | xargs -0 readlink -f | ~/.shells/print0 | xargs -0 ls -dlh --color=auto $OPT
}

cdls()
{
  builtin cd "$@" && ls
}
alias cd='cdls'

