#!/bin/bash

alias nginx='/etc/init.d/nginx'
alias shutdown='sudo /sbin/shutdown -h now'
alias reboot='sudo /sbin/shutdown -r now'
alias vimt='vim -c NERDTree'
alias blackout='timeout 1 yes ""'
alias blue='echo -e "\e[44m"; echo -e "\e[40m"'
# Set a clock by JMT.
alias setclock='ntpdate -v ntp.nict.jp'

alias remove='rm -i'
alias copy='cp -i'
alias move='mv -i'

alias ..='cd ../; echo "---------------";'
alias ...='.. ..'
alias ....='.. .. ..'

hs()
{
  expr "$2" + 1 > /dev/null 2>&1
  if [ $? -lt 2 ]; then
    history | grep -E "$1" | tail -$2
  else
    history | grep -E "$1" | tail
  fi
}

lf()
{
  while [ $1 ]
  do
    if [ "${1:0:1}" = "-" ]; then
      local OPT="$OPT $1"
    else
      local ARGS="$ARGS $1"
    fi
    shift
  done

  ls -d $(find $ARGS -maxdepth 1) | xargs readlink -f | xargs ls -dlh --color=auto $OPT
}

cdls()
{
  builtin cd "$@" && ls
}
alias cd='cdls'

