#!/bin/bash

function gc(){
  git commit -m "$*"
}

function git(){
  if [ "$1" = "fo" ]; then
    ~/bin/git-foresta --style=10 | less -RCS
  elif [ "$1" = "fa" ]; then
    ~/bin/git-foresta --all --style=10 | less -RCS
  elif [ "$1" = "fox" ]; then
    ~/bin/git-foresta --style=10 | less -RCSX
  elif [ "$1" = "fax" ]; then
    ~/bin/git-foresta --all --style=10 | less -RCSX
  elif [ "$1" = "op" ]; then
    git --no-pager log -1 | head -1 | cut -d " " -f 2
  else
    command git "$@"
  fi
}

gdiff()
{
  vim $2 "+:Gvdiff $1"
}

alias gstatus='vim "" +:Gstatus +:only'

alias g='git'
alias ga='git add'
alias gb='git branch'
alias gca='git commit --amend'
alias gd='git diff'
alias gdc='git diff --cached'
alias gl='git log'
alias gs='git status'
alias gst='git stash'
#alias gp='git pull'
#alias gplo='git pull origin master'
alias gbv='git branch -vv'

# Git config
git config --global alias.pushall '!f(){ for i in `git remote`; do git push $i $1; done; };f'
git config --global alias.fetchall '!f(){ for i in `git remote`; do git fetch --prune $i; done; };f'
git config --global alias.rename 'branch -m'
git config --global alias.graph 'log --oneline --decorate --graph'
git config --global alias.l 'log --graph --all --date=short --date-order --pretty=format:\"%C(yellow)%h%C(reset) %C(magenta)[%ad]%C(reset)%C(auto)%d%C(reset) %s %C(cyan)@%an%C(reset)\'
git config --globa alias.lb 'log --graph --date=short --date-order --pretty=format:\"%C(yellow)%h%C(reset) %C(magenta)[%ad]%C(reset)%C(auto)%d%C(reset) %s %C(cyan)@%an%C(reset)\'

git config --global merge.tool vimdiff
git config --global core.editor vim
