#!/bin/bash

function gc(){
  git commit -m "$*"
}

function git(){
  if [ "$1" = "fo" ]; then
    ~/bin/git-foresta --style=10 | less -RCS
  elif [ "$1" = "fa" ]; then
    ~/bin/git-foresta --all --style=10 | less -RCS
  elif [ "$1" = "fox" ]; then
    ~/bin/git-foresta --style=10 | less -RCSX
  elif [ "$1" = "fax" ]; then
    ~/bin/git-foresta --all --style=10 | less -RCSX
  elif [ "$1" = "op" ]; then
    git --no-pager log -1 | head -1 | cut -d " " -f 2
  else
    command git "$@"
  fi
}

gdiff()
{
  vim $2 "+:Gdiff $1"
}

alias gstatus='vim "" +:Gstatus +:only'

alias g='git'
alias ga='git add'
alias gb='git branch'
alias gca='git commit --amend'
alias gd='git diff'
alias gdc='git diff --cached'
alias gl='git log'
alias gs='git status'
alias gst='git stash'
#alias gp='git pull'
#alias gplo='git pull origin master'
alias gbv='git branch -vv'

